/* File generated with Shader Minifier 1.1.6
 * http://www.ctrl-alt-test.fr
 */
#ifndef DRAW_SHADER_H_
# define DRAW_SHADER_H_
# define VAR_IRESOLUTION "v"
# define VAR_ITIME "m"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0)uniform vec4 v;"
 "layout(location=1)uniform int m;\n"
 "#define PI 3.1415\n"
 "#define MAXSTEPS 128\n"
 "#define MINDIST 0.0001\n"
 "#define MAXDIST 20.0\n"
 "#define saturate(x)(clamp(0.0,1.0,x))\n"
 "#define f1(x)(clamp(x,0.0,1.0))\n"
 "#define rep(p,r)(mod(p-r*.5,r)-r*.5)\n"
 "vec3 f=vec3(0.,0.,0.)/255.,x=vec3(0.,0.,0.)/255.;"
 "float y=float(m)/1000.;struct pLight{vec3 position;vec3 ambiant;vec3 diffuse;vec3 specular;};"
 "float t(in vec2 v)"
 "{"
   "return fract(sin(dot(v.xy,vec2(12.9898,78.233)))*43758.5);"
 "}"
 "mat4 t(vec3 v,float y)"
 "{"
   "v=normalize(v);"
   "float x=sin(y),f=cos(y),m=1.-f;"
   "return mat4(m*v.x*v.x+f,m*v.x*v.y-v.z*x,m*v.z*v.x+v.y*x,0.,m*v.x*v.y+v.z*x,m*v.y*v.y+f,m*v.y*v.z-v.x*x,0.,m*v.z*v.x-v.y*x,m*v.y*v.z+v.x*x,m*v.z*v.z+f,0.,0.,0.,0.,1.);"
 "}"
 "float t(float v,float y,float x)"
 "{"
   "float m=clamp(.5+.5*(y-v)/x,0.,1.);"
   "return mix(y,v,m)-x*m*(1.-m);"
 "}"
 "float n(vec3 v,vec3 x,float y)"
 "{"
   "v=abs(v)-x;"
   "vec3 m=abs(v+y)-y;"
   "return min(min(length(max(vec3(v.x,m.y,m.z),0.))+min(max(v.x,max(m.y,m.z)),0.),length(max(vec3(m.x,v.y,m.z),0.))+min(max(m.x,max(v.y,m.z)),0.)),length(max(vec3(m.x,m.y,v.z),0.))+min(max(m.x,max(m.y,v.z)),0.));"
 "}"
 "float n(vec3 y,float v)"
 "{"
   "return length(y)-v;"
 "}"
 "float n(vec3 v,vec3 y,vec3 x,float m)"
 "{"
   "vec3 f=v-y,i=x-y;"
   "float s=clamp(dot(f,i)/dot(i,i),0.,1.);"
   "return length(f-i*s)-m;"
 "}"
 "float s(vec2 y,float v)"
 "{"
   "return length(y)-v;"
 "}"
 "float n(in vec2 v,in vec2 m,in vec2 y,in float x,in float f)"
 "{"
   "v*=mat2(m.x,m.y,-m.y,m.x);"
   "v.x=abs(v.x);"
   "float s=y.y*v.x>y.x*v.y?dot(v.xy,y):length(v);"
   "return sqrt(max(0.,dot(v,v)+x*x-2.*x*s))-f;"
 "}"
 "float s(in vec2 v,in vec2 y,in vec2 x)"
 "{"
   "vec2 m=v-y,f=x-y;"
   "float s=clamp(dot(m,f)/dot(f,f),0.,1.);"
   "return length(m-f*s);"
 "}"
 "float s(in vec2 v,float y,float x,float m)"
 "{"
   "vec2 f=vec2(m,x);"
   "v=v.y<0.?-v:v;"
   "vec2 i=v-f;"
   "i.x-=clamp(i.x,-y,y);"
   "vec2 r=vec2(dot(i,i),-i.y);"
   "float s=v.x*f.y-v.y*f.x;"
   "v=s<0.?-v:v;"
   "vec2 l=v-vec2(y,0);"
   "l-=f*clamp(dot(l,f)/dot(f,f),-1.,1.);"
   "r=min(r,vec2(dot(l,l),y*x-abs(s)));"
   "return sqrt(r.x)*sign(-r.y);"
 "}"
 "vec3 n(int v)"
 "{"
   "float m=float(v),f=sin(m/4.+y)+mix(2.,0.,f1(y-4.)),x=sin(2.*PI*(m/10.)+y)-mix(0.,sin(2.*PI*(m/10.)+y),f1(y/1.5-5.)),s=cos(2.*PI*(m/10.)+y)-mix(0.,cos(2.*PI*(m/10.)+y),f1(y/1.5-5.));"
   "vec3 n=vec3(f,x,s),i=n;"
   "return i;"
 "}"
 "float s(vec3 y)"
 "{"
   "vec3 v=vec3(0.),f=vec3(0.,0.,1.),x=vec3(0.,sqrt(1.),.5);"
   "return min(min(n(y,v,f,.01),n(y,f,x,.01)),n(y,x,v,.01));"
 "}"
 "vec2 p(vec3 v)"
 "{"
   "float f=0.,m=MAXDIST;"
   "for(int x=1;x<50;++x)"
     "{"
       "float i=float(x),r=2.-t(vec2(i,5.))*4.,l=2.-t(vec2(i,2.))*4.,d=-10.+mix(i/50.*10.,0.,saturate(y/20.))+mod(y*2.+t(vec2(i,1.))*20.,20.);"
       "vec3 n=v-vec3(d,l,r);"
       "float p=2.-t(vec2(i,5.))*4.;"
       "n=(t(vec3(p,l,r),y)*vec4(n,1.)).xyz;"
       "float M=s(n);"
       "if(m>M)"
         "m=M,f=i;"
     "}"
   "return vec2(m,f);"
 "}"
 "vec2 e(vec3 v)"
 "{"
   "float f=0.,m=MAXDIST;"
   "for(int y=0;y<10;++y)"
     "{"
       "float x=n(v-n(y),.1);"
       "if(m>x)"
         "m=x,f=float(y)+1.;"
     "}"
   "return vec2(m,f);"
 "}"
 "float h(vec3 v)"
 "{"
   "float f=2.-t(vec2(7.,5.))*4.,x=2.-t(vec2(2.,2.))*4.,m=2.-t(vec2(16.,5.))*4.;"
   "vec3 i=v;"
   "i=(t(vec3(m,x,f),y)*vec4(v,1.)).xyz;"
   "return n(i,vec3(.2,.2,.2)*vec3(f1(y/1.5-5./1.5)),.025);"
 "}"
 "vec3 i(vec3 v)"
 "{"
   "vec2 m=p(v),f=e(v);"
   "float x=h(v),i=t(f.x,x,.1),s=m.y,l=m.x,r=0.;"
   "if(f.x<m.x)"
     "s=f.y,l=f.x,r=1.;"
   "if(y>5.&&x<l)"
     "l=x,r=1.;"
   "return vec3(l,s,r);"
 "}"
 "vec3 r(vec3 v)"
 "{"
   "vec2 m=vec2(0.,MINDIST);"
   "return normalize(vec3(i(v+m.yxx).x-i(v-m.yxx).x,i(v+m.xyx).x-i(v-m.xyx).x,i(v+m.xxy).x-i(v-m.xxy).x));"
 "}"
 "vec4 e(vec3 v,vec3 y)"
 "{"
   "float m=MINDIST;"
   "int f=0;"
   "vec3 s=vec3(MAXDIST,-1.,-1.);"
   "for(int x=0;x<MAXSTEPS;++x)"
     "{"
       "++f;"
       "s=i(v+m*y);"
       "if(s.x<MINDIST||m>=MAXDIST)"
         "break;"
       "m+=s.x;"
     "}"
   "return vec4(m,m>MAXDIST?-1.:s.y,s.z,float(f));"
 "}"
 "vec3 e(vec3 y,vec3 v,vec3 x,pLight m,float f)"
 "{"
   "vec3 i=normalize(m.position-y),s=normalize(v-y),l=reflect(i,x),r=m.ambiant,d=max(dot(i,x),0.)*m.diffuse,n=pow(max(dot(l,s),0.),f)*m.specular;"
   "return r+.5*(d+n);"
 "}"
 "void main()"
 "{"
   "pLight m=pLight(vec3(sin(y/3.),sin(y/4.),cos(y/6.)),vec3(0.),vec3(0.),vec3(1.8));"
   "vec2 i=(2.*gl_FragCoord.xy-v.xy)/v.y;"
   "vec3 l=vec3(0.,0.,0.),d=vec3(2.,0.,0.),c=vec3(0.,1.,0.),z=normalize(l-d),p=normalize(cross(c,d)),I=normalize(cross(d,p)),M=normalize(p*i.x+I*i.y+z),a=mix(x,f,gl_FragCoord.y/v.y),g=a;"
   "vec4 P=e(d,M);"
   "g=vec3(.3,0.,1.)*P.w/float(MAXSTEPS)*4.;"
   "if(P.y>0.)"
     "{"
       "g=vec3(1.);"
       "if(P.z>0.)"
         "{"
           "vec3 T=d+P.x*M,t=r(T);"
           "g*=e(T,d,t,m,16.);"
         "}"
     "}"
   "float T=s(i+vec2(.6,.6),.05);"
   "g=mix(g,vec3(1.),smoothstep(3./v.y,0.,T));"
   "float t=PI/2.*y*2.,S=PI/4.*(1.-sin(y)/2.);"
   "T=n(i+vec2(.6,.6),vec2(sin(t),cos(t)),vec2(sin(S),cos(S)),.1,.005);"
   "g=mix(g,vec3(1.),smoothstep(4./v.y,0.,T));"
   "T=s(i,vec2(-2.,.2),vec2(.25,.2));"
   "g=mix(g,vec3(1.),smoothstep(4./v.y,0.,T));"
   "T=s(i,vec2(-.25,-.2),vec2(2.,-.2));"
   "g=mix(g,vec3(1.),smoothstep(4./v.y,0.,T));"
   "for(float h=0.;h<48.;h+=1.)"
     "T=s(i+vec2(mix(-4.,4.,h/48.)-mod(y,1.),-.275),.05,.05,.03),g=mix(g,vec3(1.),smoothstep(4./v.y,0.,T));"
   "for(float h=0.;h<48.;h+=1.)"
     "T=s(i+vec2(mix(-4.,4.,h/48.)+mod(y,1.),.275),.05,.05,.03),g=mix(g,vec3(1.),smoothstep(4./v.y,0.,T));"
   "gl_FragColor=vec4(g,1.);"
 "}";

#endif // DRAW_SHADER_H_
